AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 120
